# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  # VM1: Ubuntu (Testing)
  config.vm.define "testing" do |vm1|
    vm1.vm.box = "ubuntu/focal64"
    vm1.vm.hostname = "testing"
    vm1.vm.network "private_network", ip: "192.168.56.5"

    vm1.vm.synced_folder 'compartido_Host1/', '/home/vagrant/compartido', 
      owner: 'vagrant', group: 'vagrant'

    vm1.ssh.insert_key = true

    # Discos
    vm1.vm.disk :disk, size: "5GB", name: "testing_disk1"
    vm1.vm.disk :disk, size: "3GB", name: "testing_disk2"
    vm1.vm.disk :disk, size: "2GB", name: "testing_disk3"
    vm1.vm.disk :disk, size: "1GB", name: "testing_disk4" # no usar todavía

    vm1.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 2
      vb.name = "vmTesting"
      vb.linked_clone = true
      vb.customize ['modifyvm', :id, '--graphicscontroller', 'vmsvga']
    end

    # Provisión
    vm1.vm.provision "shell", path: "script_Enable_ssh_password.sh"
    vm1.vm.provision "shell", privileged: false, path: "script_Fix_history.sh"
    vm1.vm.provision "shell", path: "instala_paquetes.sh"
  end

  # VM2: Fedora (Production)
  config.vm.define "production" do |vm2|
    vm2.vm.box = "generic/fedora39"
    vm2.vm.hostname = "production"
    vm2.vm.network "private_network", ip: "192.168.56.6"

    vm2.vm.synced_folder 'compartido_Host2/', '/home/vagrant/compartido'

    vm2.ssh.insert_key = true

    vm2.vm.disk :disk, size: "5GB", name: "production_disk1"
    vm2.vm.disk :disk, size: "3GB", name: "production_disk2"
    vm2.vm.disk :disk, size: "2GB", name: "production_disk3"
    vm2.vm.disk :disk, size: "1GB", name: "production_disk4"

    vm2.vm.provider "virtualbox" do |vb2|
      vb2.memory = "1024"
      vb2.cpus = 2
      vb2.name = "vmProduction"
      vb2.linked_clone = true
      vb2.customize ['modifyvm', :id, '--graphicscontroller', 'vmsvga']
    end

    # Provisión
    vm2.vm.provision "shell", path: "script_Enable_ssh_password.sh"
    vm2.vm.provision "shell", privileged: false, path: "script_Fix_history.sh"
  end
end
